# Generated by Django 4.2.25 on 2025-11-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id_vitima', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_vitima', models.CharField(max_length=11, unique=True)),
                ('nome_vitima', models.CharField(max_length=150)),
                ('cep_vitima', models.CharField(max_length=8)),
                ('idade_vitima', models.IntegerField()),
                ('apelido_vitima', models.CharField(blank=True, max_length=30, null=True)),
                ('num_apelido_vitima', models.IntegerField()),
                ('cidade_vitima', models.CharField(max_length=30)),
                ('estado_vitima', models.CharField(max_length=2)),
                ('rua_vitima', models.CharField(max_length=50)),
                ('num_endereco_vitima', models.IntegerField()),
                ('complemento_endereco_vitima', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Vítima',
                'verbose_name_plural': 'Vítimas',
                'db_table': 'Vitimas',
            },
        ),
    ]
