# Generated by Django 4.2.25 on 2025-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_voluntario', models.EmailField(max_length=100)),
                ('nomecompleto_voluntario', models.CharField(max_length=150)),
                ('datanasc_voluntario', models.DateField()),
                ('sexo_voluntario', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cidade_voluntario', models.CharField(max_length=30)),
                ('estado_voluntario', models.CharField(max_length=2)),
                ('endereco_voluntario', models.CharField(max_length=50)),
                ('telefone_voluntario', models.CharField(max_length=9)),
                ('instagram_voluntario', models.CharField(max_length=30)),
                ('cpf_voluntario', models.CharField(max_length=14, unique=True)),
                ('rg_voluntario', models.CharField(max_length=9)),
                ('cpfupload_voluntario', models.BooleanField()),
                ('fotoupload_voluntario', models.BooleanField()),
                ('termoupload_voluntario', models.BooleanField()),
            ],
            options={
                'db_table': 'Voluntarios',
            },
        ),
    ]
