# Generated by Django 4.2.25 on 2025-11-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='id',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='id_voluntario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
