# Generated by Django 4.2.25 on 2025-11-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_remove_voluntario_id_voluntario_id_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id_estagiario', models.AutoField(primary_key=True, serialize=False)),
                ('curso_estagiario', models.CharField(max_length=20)),
                ('periodo_estagiario', models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período'), ('5', '5º Período'), ('6', '6º Período'), ('7', '7º Período'), ('8', '8º Período'), ('9', '9º Período'), ('10', '10º Período')], max_length=2)),
                ('id_voluntario', models.OneToOneField(db_column='id_voluntario', on_delete=django.db.models.deletion.CASCADE, related_name='estagiario', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Estagiário',
                'verbose_name_plural': 'Estagiários',
                'db_table': 'Estagiarios',
            },
        ),
    ]
