# Generated by Django 4.2.25 on 2025-11-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_estagiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id_advogado', models.AutoField(primary_key=True, serialize=False)),
                ('oab_advogado', models.CharField(max_length=9, unique=True)),
                ('id_voluntario', models.OneToOneField(db_column='id_voluntario', on_delete=django.db.models.deletion.CASCADE, related_name='advogado', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'db_table': 'Advogados',
            },
        ),
    ]
