# Generated by Django 4.2.25 on 2025-11-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0004_advogado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacharel',
            fields=[
                ('id_bacharel', models.AutoField(primary_key=True, serialize=False)),
                ('cursoformacao_bacharel', models.CharField(max_length=20)),
                ('id_voluntario', models.OneToOneField(db_column='id_voluntario', on_delete=django.db.models.deletion.CASCADE, related_name='bacharel', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Bacharel',
                'verbose_name_plural': 'Bacharéis',
                'db_table': 'Bachareis',
            },
        ),
    ]
