# Generated by Django 4.2.25 on 2025-11-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0005_bacharel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeEstagiario',
            fields=[
                ('id_disponibilidadeestagiario', models.AutoField(primary_key=True, serialize=False)),
                ('diasemana_estagiario', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=20)),
                ('iniciodisponibilidade_estagiario', models.DateTimeField()),
                ('fimdisponibilidade_estagiario', models.DateTimeField()),
                ('id_estagiario', models.ForeignKey(db_column='id_estagiario', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='voluntarios.estagiario')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Estagiário',
                'verbose_name_plural': 'Disponibilidades dos Estagiários',
                'db_table': 'DisponibilidadesEstagiarios',
            },
        ),
    ]
