# Generated by Django 4.2.25 on 2025-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0006_disponibilidadeestagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeestagiario',
            name='fimdisponibilidade_estagiario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidadeestagiario',
            name='iniciodisponibilidade_estagiario',
            field=models.TimeField(),
        ),
    ]
